os: linux

services:
  - docker

script:
  - cp .env.example .env
  - docker-compose -f docker-compose.ci.yml up -d
  - docker-compose ps
  - docker-compose exec app /bin/bash -c "yarn test"

notifications:
  email:
    - we.universalnatives@gmail.com
