# Inspired by https://github.com/postlight/headless-wp-starter

FROM wordpress

RUN sed -i 's/80/8080/' /etc/apache2/ports.conf /etc/apache2/sites-enabled/000-default.conf

RUN mv "$PHP_INI_DIR"/php.ini-development "$PHP_INI_DIR"/php.ini

# install_wordpress.sh dependencies
RUN apt-get update; \
  apt-get install -yq netcat mariadb-client

# wp-cli
RUN curl -sL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o wp; \
  chmod +x wp; \
  mv wp /usr/local/bin/; \
  mkdir /var/www/.wp-cli; \
  chown www-data:www-data /var/www/.wp-cli

# install_wordpress.sh script
COPY --chown=www-data:www-data ./setup/install_wordpress.sh /usr/local/bin/install_wordpress
RUN chmod +x /usr/local/bin/install_wordpress

# ensure wordpress has write permission on linux host
# https://github.com/postlight/headless-wp-starter/issues/202
RUN chown -R www-data:www-data /var/www/html

EXPOSE 8080