<?php
/**
 * Register fields for custom post types.
 *
 * @package  UN_Headless_WP
 */

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5f2383fe0fbda',
        'title' => 'Content Grid fields',
        'fields' => array(
            array(
                'key' => 'field_5f2384054d9aa',
                'label' => 'Type',
                'name' => 'type',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'team' => 'Team Grid',
                    'articles' => 'Article Grid',
                ),
                'default_value' => 'team',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5f23845d4d9ab',
                'label' => 'Team Members',
                'name' => 'team_members',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f2384054d9aa',
                            'operator' => '==',
                            'value' => 'team',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'teammember',
                ),
                'taxonomy' => '',
                'filters' => array(
                    0 => 'search',
                    1 => 'post_type',
                    2 => 'taxonomy',
                ),
                'elements' => '',
                'min' => '',
                'max' => '',
                'return_format' => 'object',
            ),
            array(
                'key' => 'field_5f2384b74d9ac',
                'label' => 'Articles',
                'name' => 'articles',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f2384054d9aa',
                            'operator' => '==',
                            'value' => 'articles',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'contentwithpreview',
                ),
                'taxonomy' => '',
                'filters' => array(
                    0 => 'search',
                    1 => 'post_type',
                    2 => 'taxonomy',
                ),
                'elements' => '',
                'min' => '',
                'max' => '',
                'return_format' => 'object',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'contentgrid',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f237e00ee2d4',
        'title' => 'Team Member fields',
        'fields' => array(
            array(
                'key' => 'field_5f237e0788cb9',
                'label' => 'Bio',
                'name' => 'bio',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5f2381ef75081',
                'label' => 'Photo',
                'name' => 'photo',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f237e8a88cba',
                'label' => 'Career',
                'name' => 'career',
                'type' => 'textarea',
                'instructions' => 'One value per line',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_5f237f5788cbb',
                'label' => 'Education',
                'name' => 'education',
                'type' => 'textarea',
                'instructions' => 'One value per line',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_5f237f7588cbc',
                'label' => 'Country',
                'name' => 'country',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Afghanistan' => 'Afghanistan',
                    'Akrotiri' => 'Akrotiri',
                    'Albania' => 'Albania',
                    'Algeria' => 'Algeria',
                    'American Samoa' => 'American Samoa',
                    'Andorra' => 'Andorra',
                    'Angola' => 'Angola',
                    'Anguilla' => 'Anguilla',
                    'Antarctica' => 'Antarctica',
                    'Antigua and Barbuda' => 'Antigua and Barbuda',
                    'Argentina' => 'Argentina',
                    'Armenia' => 'Armenia',
                    'Aruba' => 'Aruba',
                    'Ashmore and Cartier Islands' => 'Ashmore and Cartier Islands',
                    'Australia' => 'Australia',
                    'Austria' => 'Austria',
                    'Azerbaijan' => 'Azerbaijan',
                    'Bahamas, The' => 'Bahamas, The',
                    'Bahrain' => 'Bahrain',
                    'Bangladesh' => 'Bangladesh',
                    'Barbados' => 'Barbados',
                    'Bassas da India' => 'Bassas da India',
                    'Belarus' => 'Belarus',
                    'Belgium' => 'Belgium',
                    'Belize' => 'Belize',
                    'Benin' => 'Benin',
                    'Bermuda' => 'Bermuda',
                    'Bhutan' => 'Bhutan',
                    'Bolivia' => 'Bolivia',
                    'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
                    'Botswana' => 'Botswana',
                    'Bouvet Island' => 'Bouvet Island',
                    'Brazil' => 'Brazil',
                    'British Indian Ocean Territory' => 'British Indian Ocean Territory',
                    'British Virgin Islands' => 'British Virgin Islands',
                    'Brunei' => 'Brunei',
                    'Bulgaria' => 'Bulgaria',
                    'Burkina Faso' => 'Burkina Faso',
                    'Burma' => 'Burma',
                    'Burundi' => 'Burundi',
                    'Cambodia' => 'Cambodia',
                    'Cameroon' => 'Cameroon',
                    'Canada' => 'Canada',
                    'Cape Verde' => 'Cape Verde',
                    'Cayman Islands' => 'Cayman Islands',
                    'Central African Republic' => 'Central African Republic',
                    'Chad' => 'Chad',
                    'Chile' => 'Chile',
                    'China' => 'China',
                    'Christmas Island' => 'Christmas Island',
                    'Clipperton Island' => 'Clipperton Island',
                    'Cocos (Keeling) Islands' => 'Cocos (Keeling) Islands',
                    'Colombia' => 'Colombia',
                    'Comoros' => 'Comoros',
                    'Congo, Democratic Republic of the' => 'Congo, Democratic Republic of the',
                    'Congo, Republic of the' => 'Congo, Republic of the',
                    'Cook Islands' => 'Cook Islands',
                    'Coral Sea Islands' => 'Coral Sea Islands',
                    'Costa Rica' => 'Costa Rica',
                    'Cote d\'Ivoire' => 'Cote d\'Ivoire',
                    'Croatia' => 'Croatia',
                    'Cuba' => 'Cuba',
                    'Cyprus' => 'Cyprus',
                    'Czech Republic' => 'Czech Republic',
                    'Denmark' => 'Denmark',
                    'Dhekelia' => 'Dhekelia',
                    'Djibouti' => 'Djibouti',
                    'Dominica' => 'Dominica',
                    'Dominican Republic' => 'Dominican Republic',
                    'Ecuador' => 'Ecuador',
                    'Egypt' => 'Egypt',
                    'El Salvador' => 'El Salvador',
                    'Equatorial Guinea' => 'Equatorial Guinea',
                    'Eritrea' => 'Eritrea',
                    'Estonia' => 'Estonia',
                    'Ethiopia' => 'Ethiopia',
                    'Europa Island' => 'Europa Island',
                    'Falkland Islands (Islas Malvinas)' => 'Falkland Islands (Islas Malvinas)',
                    'Faroe Islands' => 'Faroe Islands',
                    'Fiji' => 'Fiji',
                    'Finland' => 'Finland',
                    'France' => 'France',
                    'French Guiana' => 'French Guiana',
                    'French Polynesia' => 'French Polynesia',
                    'French Southern and Antarctic Lands' => 'French Southern and Antarctic Lands',
                    'Gabon' => 'Gabon',
                    'Gambia, The' => 'Gambia, The',
                    'Gaza Strip' => 'Gaza Strip',
                    'Georgia' => 'Georgia',
                    'Germany' => 'Germany',
                    'Ghana' => 'Ghana',
                    'Gibraltar' => 'Gibraltar',
                    'Glorioso Islands' => 'Glorioso Islands',
                    'Greece' => 'Greece',
                    'Greenland' => 'Greenland',
                    'Grenada' => 'Grenada',
                    'Guadeloupe' => 'Guadeloupe',
                    'Guam' => 'Guam',
                    'Guatemala' => 'Guatemala',
                    'Guernsey' => 'Guernsey',
                    'Guinea' => 'Guinea',
                    'Guinea-Bissau' => 'Guinea-Bissau',
                    'Guyana' => 'Guyana',
                    'Haiti' => 'Haiti',
                    'Heard Island and McDonald Islands' => 'Heard Island and McDonald Islands',
                    'Holy See (Vatican City)' => 'Holy See (Vatican City)',
                    'Honduras' => 'Honduras',
                    'Hong Kong' => 'Hong Kong',
                    'Hungary' => 'Hungary',
                    'Iceland' => 'Iceland',
                    'India' => 'India',
                    'Indonesia' => 'Indonesia',
                    'Iran' => 'Iran',
                    'Iraq' => 'Iraq',
                    'Ireland' => 'Ireland',
                    'Isle of Man' => 'Isle of Man',
                    'Israel' => 'Israel',
                    'Italy' => 'Italy',
                    'Jamaica' => 'Jamaica',
                    'Jan Mayen' => 'Jan Mayen',
                    'Japan' => 'Japan',
                    'Jersey' => 'Jersey',
                    'Jordan' => 'Jordan',
                    'Juan de Nova Island' => 'Juan de Nova Island',
                    'Kazakhstan' => 'Kazakhstan',
                    'Kenya' => 'Kenya',
                    'Kiribati' => 'Kiribati',
                    'Korea, North' => 'Korea, North',
                    'Korea, South' => 'Korea, South',
                    'Kuwait' => 'Kuwait',
                    'Kyrgyzstan' => 'Kyrgyzstan',
                    'Laos' => 'Laos',
                    'Latvia' => 'Latvia',
                    'Lebanon' => 'Lebanon',
                    'Lesotho' => 'Lesotho',
                    'Liberia' => 'Liberia',
                    'Libya' => 'Libya',
                    'Liechtenstein' => 'Liechtenstein',
                    'Lithuania' => 'Lithuania',
                    'Luxembourg' => 'Luxembourg',
                    'Macau' => 'Macau',
                    'Macedonia' => 'Macedonia',
                    'Madagascar' => 'Madagascar',
                    'Malawi' => 'Malawi',
                    'Malaysia' => 'Malaysia',
                    'Maldives' => 'Maldives',
                    'Mali' => 'Mali',
                    'Malta' => 'Malta',
                    'Marshall Islands' => 'Marshall Islands',
                    'Martinique' => 'Martinique',
                    'Mauritania' => 'Mauritania',
                    'Mauritius' => 'Mauritius',
                    'Mayotte' => 'Mayotte',
                    'Mexico' => 'Mexico',
                    'Micronesia, Federated States of' => 'Micronesia, Federated States of',
                    'Moldova' => 'Moldova',
                    'Monaco' => 'Monaco',
                    'Mongolia' => 'Mongolia',
                    'Montserrat' => 'Montserrat',
                    'Morocco' => 'Morocco',
                    'Mozambique' => 'Mozambique',
                    'Namibia' => 'Namibia',
                    'Nauru' => 'Nauru',
                    'Navassa Island' => 'Navassa Island',
                    'Nepal' => 'Nepal',
                    'Netherlands' => 'Netherlands',
                    'Netherlands Antilles' => 'Netherlands Antilles',
                    'New Caledonia' => 'New Caledonia',
                    'New Zealand' => 'New Zealand',
                    'Nicaragua' => 'Nicaragua',
                    'Niger' => 'Niger',
                    'Nigeria' => 'Nigeria',
                    'Niue' => 'Niue',
                    'Norfolk Island' => 'Norfolk Island',
                    'Northern Mariana Islands' => 'Northern Mariana Islands',
                    'Norway' => 'Norway',
                    'Oman' => 'Oman',
                    'Pakistan' => 'Pakistan',
                    'Palau' => 'Palau',
                    'Panama' => 'Panama',
                    'Papua New Guinea' => 'Papua New Guinea',
                    'Paracel Islands' => 'Paracel Islands',
                    'Paraguay' => 'Paraguay',
                    'Peru' => 'Peru',
                    'Philippines' => 'Philippines',
                    'Pitcairn Islands' => 'Pitcairn Islands',
                    'Poland' => 'Poland',
                    'Portugal' => 'Portugal',
                    'Puerto Rico' => 'Puerto Rico',
                    'Qatar' => 'Qatar',
                    'Reunion' => 'Reunion',
                    'Romania' => 'Romania',
                    'Russia' => 'Russia',
                    'Rwanda' => 'Rwanda',
                    'Saint Helena' => 'Saint Helena',
                    'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
                    'Saint Lucia' => 'Saint Lucia',
                    'Saint Pierre and Miquelon' => 'Saint Pierre and Miquelon',
                    'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
                    'Samoa' => 'Samoa',
                    'San Marino' => 'San Marino',
                    'Sao Tome and Principe' => 'Sao Tome and Principe',
                    'Saudi Arabia' => 'Saudi Arabia',
                    'Senegal' => 'Senegal',
                    'Serbia and Montenegro' => 'Serbia and Montenegro',
                    'Seychelles' => 'Seychelles',
                    'Sierra Leone' => 'Sierra Leone',
                    'Singapore' => 'Singapore',
                    'Slovakia' => 'Slovakia',
                    'Slovenia' => 'Slovenia',
                    'Solomon Islands' => 'Solomon Islands',
                    'Somalia' => 'Somalia',
                    'South Africa' => 'South Africa',
                    'South Georgia and the South Sandwich Islands' => 'South Georgia and the South Sandwich Islands',
                    'Spain' => 'Spain',
                    'Spratly Islands' => 'Spratly Islands',
                    'Sri Lanka' => 'Sri Lanka',
                    'Sudan' => 'Sudan',
                    'Suriname' => 'Suriname',
                    'Svalbard' => 'Svalbard',
                    'Swaziland' => 'Swaziland',
                    'Sweden' => 'Sweden',
                    'Switzerland' => 'Switzerland',
                    'Syria' => 'Syria',
                    'Taiwan' => 'Taiwan',
                    'Tajikistan' => 'Tajikistan',
                    'Tanzania' => 'Tanzania',
                    'Thailand' => 'Thailand',
                    'Timor-Leste' => 'Timor-Leste',
                    'Togo' => 'Togo',
                    'Tokelau' => 'Tokelau',
                    'Tonga' => 'Tonga',
                    'Trinidad and Tobago' => 'Trinidad and Tobago',
                    'Tromelin Island' => 'Tromelin Island',
                    'Tunisia' => 'Tunisia',
                    'Turkey' => 'Turkey',
                    'Turkmenistan' => 'Turkmenistan',
                    'Turks and Caicos Islands' => 'Turks and Caicos Islands',
                    'Tuvalu' => 'Tuvalu',
                    'Uganda' => 'Uganda',
                    'Ukraine' => 'Ukraine',
                    'United Arab Emirates' => 'United Arab Emirates',
                    'United Kingdom' => 'United Kingdom',
                    'United States' => 'United States',
                    'Uruguay' => 'Uruguay',
                    'Uzbekistan' => 'Uzbekistan',
                    'Vanuatu' => 'Vanuatu',
                    'Venezuela' => 'Venezuela',
                    'Vietnam' => 'Vietnam',
                    'Virgin Islands' => 'Virgin Islands',
                    'Wake Island' => 'Wake Island',
                    'Wallis and Futuna' => 'Wallis and Futuna',
                    'West Bank' => 'West Bank',
                    'Western Sahara' => 'Western Sahara',
                    'Yemen' => 'Yemen',
                    'Zambia' => 'Zambia',
                    'Zimbabwe' => 'Zimbabwe',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5f2380b088cbd',
                'label' => 'LinkedIn Profile',
                'name' => 'linkedin_profile',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'teammember',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f1b1096c547f',
        'title' => 'Carousel fields',
        'fields' => array(
            array(
                'key' => 'field_5f1b759a46f96',
                'label' => 'Slide 1 Image',
                'name' => 'slide_1_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f1b75e546f97',
                'label' => 'Slide 1 Description',
                'name' => 'slide_1_description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_5f1b76ff46f98',
                'label' => 'Slide 2 Image',
                'name' => 'slide_2_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f1b775146f9c',
                'label' => 'Slide 2 Description',
                'name' => 'slide_2_description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_5f1b772446f99',
                'label' => 'Slide 3 Image',
                'name' => 'slide_3_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f1b775d46f9d',
                'label' => 'Slide 3 Description',
                'name' => 'slide_3_description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_5f1b773546f9a',
                'label' => 'Slide 4 Image',
                'name' => 'slide_4_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f1b776846f9e',
                'label' => 'Slide 4 Description',
                'name' => 'slide_4_description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_5f1b774446f9b',
                'label' => 'Slide 5 Image',
                'name' => 'slide_5_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f1b777446f9f',
                'label' => 'Slide 5 Description',
                'name' => 'slide_5_description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'br',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'carousel',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f18edd5e7c1f',
        'title' => 'Navlink fields',
        'fields' => array(
            array(
                'key' => 'field_5f18ede138ca7',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'unpage',
                'field_type' => 'radio',
                'allow_null' => 0,
                'add_term' => 1,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'object',
                'multiple' => 0,
            ),
            array(
                'key' => 'field_5f18f94788c7c',
                'label' => 'Is Primary',
                'name' => 'is_primary',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'navlink',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f111686a433e',
        'title' => 'Page Section fields',
        'fields' => array(
            array(
                'key' => 'field_5f11168cc7c1d',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'hero',
                    1 => 'contentwithpreview',
                    2 => 'carousel',
                    3 => 'contentgrid',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'object',
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'pagesection',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f0e5822489d7',
        'title' => 'ContentWithPreview fields',
        'fields' => array(
            array(
                'key' => 'field_5f0e582e4b380',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5f0e58934b381',
                'label' => 'Image Preview',
                'name' => 'image_preview',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f0e58be4b382',
                'label' => 'Video Preview',
                'name' => 'video_preview',
                'type' => 'oembed',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'width' => '',
                'height' => '',
            ),
            array(
                'key' => 'field_5f0e62aab8f87',
                'label' => 'Preview Position',
                'name' => 'preview_position',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                ),
                'default_value' => 'left',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5f1474eda074c',
                'label' => 'CTA',
                'name' => 'cta',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'contentwithpreview',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5f0bc33f95cc9',
        'title' => 'Hero fields',
        'fields' => array(
            array(
                'key' => 'field_5f0bc37e15c39',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f0bc38915c3a',
                'label' => 'Description',
                'name' => 'description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5f0bc39a15c3b',
                'label' => 'Primary CTA',
                'name' => 'primary_cta',
                'type' => 'link',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_5f0bc40315c3c',
                'label' => 'Secondary CTA',
                'name' => 'secondary_cta',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_5f1a45b0fa646',
                'label' => 'Background Image',
                'name' => 'background_image',
                'type' => 'image',
                'instructions' => 'Select one of background video or image but not both. If both are selected, image will take precedence.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f14f49d81988',
                'label' => 'Background Video',
                'name' => 'background_video',
                'type' => 'file',
                'instructions' => 'Select one of background video or image but not both. If both are selected, image will take precedence.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'hero',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;